source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'App' do
  pod 'Foo', path: 'Foo.podspec'
end

target 'DummyTarget' do
  pod 'Forkable', source: 'https://github.com/Private/SpecsForks.git'
  pod 'UsesForkable', source: 'https://github.com/Private/SpecsForks.git'
end
